# Conexão Reporter - Exploratory Analysis

In [1]:
import numpy as np
import pandas as pd
from serenata_toolbox.datasets import Datasets

In [3]:
datasets = Datasets('../data/')
datasets.downloader.download('2017-07-04-reimbursements.xz')

Downloading 2017-07-04-reimbursements.xz: 100%|██████████| 34.1M/34.1M [01:15<00:00, 452Kb/s]

In [18]:
datasets.downloader.download('2017-07-04-suspicions.xz')

Downloading 2017-07-04-suspicions.xz: 100%|██████████| 2.22M/2.22M [00:05<00:00, 419Kb/s]

In [4]:
reimbursements = pd.read_csv('../data/2017-07-04-reimbursements.xz',
                      dtype={'applicant_id': np.str,
                             'cnpj_cpf': np.str,
                             'congressperson_id': np.str,
                             'subquota_number': np.str,
                             'document_id': np.int},
                      low_memory=False)

In [5]:
reimbursements.columns

Index(['year', 'applicant_id', 'document_id', 'reimbursement_value_total',
       'total_net_value', 'reimbursement_numbers', 'congressperson_name',
       'congressperson_id', 'congressperson_document', 'term', 'state',
       'party', 'term_id', 'subquota_number', 'subquota_description',
       'subquota_group_id', 'subquota_group_description', 'supplier',
       'cnpj_cpf', 'document_number', 'document_type', 'issue_date',
       'document_value', 'remark_value', 'net_values', 'month', 'installment',
       'passenger', 'leg_of_the_trip', 'batch_number', 'reimbursement_values'],
      dtype='object')

## Find current term biggest consumers

The idea is to find the top 3 lower house representatives with the highest amount of reimbursements considering all the years in office but that was elected in the last election. The current term started in 2015.

we can find a table of lower house representatives in office using [this link](http://www2.camara.leg.br/deputados/pesquisa/arquivos/arquivo-formato-excel-com-informacoes-dos-deputados-1) bt there we only have 512 instead of the 513. So is a safer route to list the congresspeople using the reimbursements.

In [6]:
current_term_reimbursements = reimbursements[reimbursements['year'] >= 2015].reset_index(drop=True)
current_term_reimbursements.shape

(466273, 31)

In [8]:
len(list(set(current_term_reimbursements['congressperson_name'])))

808

Remember that this number doesn't match 513 because we have names also for some leadership and seconds.

In [71]:
current_term_congresspeople = list(set(current_term_reimbursements['congressperson_name']))

sorted(current_term_congresspeople)

['ABEL MESQUITA JR.',
 'ABELARDO CAMARINHA',
 'ABELARDO LUPION',
 'ACELINO POPÓ',
 'ADAIL CARNEIRO',
 'ADALBERTO CAVALCANTI',
 'ADELMO CARNEIRO LEÃO',
 'ADELSON BARRETO',
 'ADEMIR CAMILO',
 'ADILTON SACHETTI',
 'ADRIAN',
 'ADÉRMIS MARINI',
 'AELTON FREITAS',
 'AFONSO FLORENCE',
 'AFONSO HAMM',
 'AFONSO MOTTA',
 'AGUINALDO RIBEIRO',
 'AKIRA OTSUBO',
 'ALAN RICK',
 'ALBERTO FILHO',
 'ALBERTO FRAGA',
 'ALCEU MOREIRA',
 'ALESSANDRO MOLON',
 'ALEX CANZIANI',
 'ALEX MANENTE',
 'ALEXANDRE BALDY',
 'ALEXANDRE LEITE',
 'ALEXANDRE ROSO',
 'ALEXANDRE SANTOS',
 'ALEXANDRE SERFIOTIS',
 'ALEXANDRE SILVEIRA',
 'ALEXANDRE TOLEDO',
 'ALEXANDRE VALLE',
 'ALFREDO KAEFER',
 'ALFREDO NASCIMENTO',
 'ALFREDO SIRKIS',
 'ALICE PORTUGAL',
 'ALIEL MACHADO',
 'ALINE CORRÊA',
 'ALMEIDA LIMA',
 'ALTINEU CÔRTES',
 'ALUISIO MENDES',
 'AMAURI TEIXEIRA',
 'AMIR LANDO',
 'ANA PERUGINI',
 'ANDERSON FERREIRA',
 'ANDRE MOURA',
 'ANDREIA ZITO',
 'ANDRES SANCHEZ',
 'ANDRÉ ABDON',
 'ANDRÉ AMARAL',
 'ANDRÉ DE PAULA',
 'ANDRÉ FIGUEIREDO',
 'ANDRÉ FUFUCA',
 'ANDRÉ ZACHAROW',
 'ANGELA ALBINO',
 'ANGELIM',
 'ANGELO VANHONI',
 'ANSELMO DE JESUS',
 'ANTHONY GAROTINHO',
 'ANTONIO BALHMANN',
 'ANTONIO BRITO',
 'ANTONIO BULHÕES',
 'ANTONIO CARLOS MENDES THAME',
 'ANTONIO IMBASSAHY',
 'ANTÔNIA LÚCIA',
 'ANTÔNIO JÁCOME',
 'ANÍBAL GOMES',
 'ARIOSTO HOLANDA',
 'ARLINDO CHINAGLIA',
 'ARMANDO VERGÍLIO',
 'ARNALDO FARIA DE SÁ',
 'ARNALDO JARDIM',
 'ARNALDO JORDY',
 'ARNON BEZERRA',
 'AROLDE DE OLIVEIRA',
 'ARTHUR LIRA',
 'ARTHUR OLIVEIRA MAIA',
 'ARTHUR VIRGÍLIO BISNETO',
 'ASSIS CARVALHO',
 'ASSIS DO COUTO',
 'ASSIS MELO',
 'AUGUSTO CARVALHO',
 'AUGUSTO COUTINHO',
 'AUREO',
 'BACELAR',
 'BALEIA ROSSI',
 'BEBETO',
 'BENEDITA DA SILVA',
 'BENITO GAMA',
 'BENJAMIN MARANHÃO',
 'BERINHO BANTIM',
 'BERNARDO SANTANA DE VASCONCELLOS',
 'BETINHO GOMES',
 'BETINHO ROSADO',
 'BETO ALBUQUERQUE',
 'BETO FARO',
 'BETO MANSUR',
 'BETO ROSADO',
 'BETO SALAME',
 'BIFFI',
 'BILAC PINTO',
 'BOHN GASS',
 'BONIFÁCIO DE ANDRADA',
 'BOSCO COSTA',
 'BRUNA FURLAN',
 'BRUNNY',
 'BRUNO ARAÚJO',
 'BRUNO COVAS',
 'BRUNO RODRIGUES',
 'CABO DACIOLO',
 'CABO SABINO',
 'CABUÇU BORGES',
 'CACÁ LEÃO',
 'CAETANO',
 'CAIO NARCIO',
 'CAJAR NARDES',
 'CAPITÃO AUGUSTO',
 'CAPITÃO FÁBIO ABREU',
 'CARLOS ALBERTO LERÉIA',
 'CARLOS ANDRADE',
 'CARLOS BEZERRA',
 'CARLOS EDUARDO CADOCA',
 'CARLOS GOMES',
 'CARLOS HENRIQUE GAGUIM',
 'CARLOS MAGNO',
 'CARLOS MANATO',
 'CARLOS MARTINS',
 'CARLOS MARUN',
 'CARLOS MELLES',
 'CARLOS SAMPAIO',
 'CARLOS ZARATTINI',
 'CARMEN ZANOTTO',
 'CELSO JACOB',
 'CELSO MALDANER',
 'CELSO PANSERA',
 'CELSO RUSSOMANNO',
 'CESAR SOUZA',
 'CHICO ALENCAR',
 "CHICO D'ANGELO",
 'CHICO DAS VERDURAS',
 'CHICO LOPES',
 'CHRISTIANE DE SOUZA YARED',
 'CLARISSA GAROTINHO',
 'CLAUDIO CAJADO',
 'CLEBER VERDE',
 'CLÁUDIO PUTY',
 'CONCEIÇÃO SAMPAIO',
 'COVATTI FILHO',
 'CREUZA PEREIRA',
 'CRISTIANE BRASIL',
 'CÂNDIDO VACCAREZZA',
 'CÉLIO SILVEIRA',
 'CÉSAR HALUM',
 'CÉSAR MESSIAS',
 'CÍCERO ALMEIDA',
 'DAGOBERTO NOGUEIRA',
 'DALVA FIGUEIREDO',
 'DAMIÃO FELICIANO',
 'DANIEL ALMEIDA',
 'DANIEL COELHO',
 'DANIEL VILELA',
 'DANILO CABRAL',
 'DANILO FORTE',
 'DANRLEI DE DEUS HINTERHOLZ',
 'DARCÍSIO PERONDI',
 'DAVI ALCOLUMBRE',
 'DAVI ALVES SILVA JÚNIOR',
 'DAVIDSON MAGALHÃES',
 'DEJORGE PATRÍCIO',
 'DELEGADO EDSON MOREIRA',
 'DELEGADO FRANCISCHINI',
 'DELEGADO PROTÓGENES',
 'DELEGADO WALDIR',
 'DELEGADO ÉDER MAURO',
 'DELEY',
 'DENILSON TEIXEIRA',
 'DEOCLIDES MACEDO',
 'DEVANIR RIBEIRO',
 'DIEGO ANDRADE',
 'DIEGO GARCIA',
 'DILCEU SPERAFICO',
 'DIMAS FABIANO',
 'DOMINGOS DUTRA',
 'DOMINGOS NETO',
 'DOMINGOS SÁVIO',
 'DR. ADILSON SOARES',
 'DR. CARLOS ALBERTO',
 'DR. GRILO',
 'DR. JORGE SILVA',
 'DR. JOÃO',
 'DR. LUIZ FERNANDO',
 'DR. PAULO CÉSAR',
 'DR. ROSINHA',
 'DR. SINVAL MALHEIROS',
 'DR. UBIALI',
 'DRA. ELAINE ABISSAMRA',
 'DUARTE NOGUEIRA',
 'DUDIMAR PAXIUBA',
 'DULCE MIRANDA',
 'DÂMINA PEREIRA',
 'DÉCIO LIMA',
 'EDINHO ARAÚJO',
 'EDINHO BEZ',
 'EDIO LOPES',
 'EDMAR ARRUDA',
 'EDMILSON RODRIGUES',
 'EDSON EZEQUIEL',
 'EDSON PIMENTA',
 'EDSON SANTOS',
 'EDSON SILVA',
 'EDUARDO BARBOSA',
 'EDUARDO BOLSONARO',
 'EDUARDO CUNHA',
 'EDUARDO CURY',
 'EDUARDO DA FONTE',
 'EDUARDO GOMES',
 'EDUARDO SCIARRA',
 'EFRAIM FILHO',
 'ELCIONE BARBALHO',
 'ELEUSES PAIVA',
 'ELI CORRÊA FILHO',
 'ELIENE LIMA',
 'ELIZEU DIONIZIO',
 'ELIZIANE GAMA',
 'ELMAR NASCIMENTO',
 'EMANUEL FERNANDES',
 'EMILIANO JOSÉ',
 'ENIO BACCI',
 'ENIO VERRI',
 'ERIKA KOKAY',
 'ERIVELTON SANTANA',
 'EROS BIONDINI',
 'ESPERIDIÃO AMIN',
 'EUDES XAVIER',
 'EURICO JÚNIOR',
 'EVAIR VIEIRA DE MELO',
 'EVANDRO GUSSI',
 'EVANDRO MILHOMEN',
 'EVANDRO ROMAN',
 'EXPEDITO NETTO',
 'EZEQUIEL FONSECA',
 'EZEQUIEL TEIXEIRA',
 'FABIANO HORTA',
 'FABIO GARCIA',
 'FABIO REIS',
 'FABRICIO OLIVEIRA',
 'FAUSTO PINATO',
 'FELIPE BORNIER',
 'FELIPE MAIA',
 'FERNANDO COELHO FILHO',
 'FERNANDO FERRO',
 'FERNANDO JORDÃO',
 'FERNANDO MARRONI',
 'FERNANDO MONTEIRO',
 'FERNANDO TORRES',
 'FERNANDO ZACHIA',
 'FLAVIANO MELO',
 'FLAVINHO',
 'FLAVIO NOGUEIRA',
 'FLORIANO PESARO',
 'FLÁVIA MORAIS',
 'FRANCISCO CHAGAS',
 'FRANCISCO CHAPADINHA',
 'FRANCISCO FLORIANO',
 'FRANCISCO PRACIANO',
 'FRANCISCO TENÓRIO',
 'FRANKLIN',
 'FÁBIO FARIA',
 'FÁBIO MITIDIERI',
 'FÁBIO RAMALHO',
 'FÁBIO SOUSA',
 'FÁBIO SOUTO',
 'FÁBIO TRAD',
 'FÁTIMA BEZERRA',
 'FÁTIMA PELAES',
 'FÉLIX MENDONÇA JÚNIOR',
 'GABRIEL CHALITA',
 'GABRIEL GUIMARÃES',
 'GASTÃO VIEIRA',
 'GENECIAS NORONHA',
 'GEORGE HILTON',
 'GEOVANIA DE SÁ',
 'GERALDO RESENDE',
 'GERALDO SIMÕES',
 'GERALDO THADEU',
 'GIACOBO',
 'GILBERTO COUTINHO',
 'GILBERTO NASCIMENTO',
 'GIOVANI CHERINI',
 'GIOVANI FELTES',
 'GIOVANNI QUEIROZ',
 'GIROTO',
 'GIUSEPPE VECCI',
 'GIVALDO CARIMBÃO',
 'GIVALDO VIEIRA',
 'GLADSON CAMELI',
 'GLAUBER BRAGA',
 'GONZAGA PATRIOTA',
 'GORETE PEREIRA',
 'GOULART',
 'GUILHERME CAMPOS',
 'GUILHERME COELHO',
 'GUILHERME MUSSI',
 'GUSTAVO PETTA',
 'HEITOR SCHUCH',
 'HELCIO SILVA',
 'HELDER SALOMÃO',
 'HENRIQUE AFONSO',
 'HENRIQUE EDUARDO ALVES',
 'HENRIQUE FONTANA',
 'HERCULANO PASSOS',
 'HERMES PARCIANELLO',
 'HERÁCLITO FORTES',
 'HEULER CRUVINEL',
 'HILDO ROCHA',
 'HIRAN GONÇALVES',
 'HISSA ABRAHÃO',
 'HUGO LEAL',
 'HUGO MOTTA',
 'HUGO NAPOLEÃO',
 'HÉLIO LEITE',
 'HÉLIO SANTOS',
 'IARA BERNARDI',
 'ILDON MARQUES',
 'INDIO DA COSTA',
 'IRACEMA PORTELLA',
 'IRAJÁ ABREU',
 'IRINY LOPES',
 'IRMÃO LAZARO',
 'IVAN VALENTE',
 'IZALCI LUCAS',
 'IZAQUE SILVA',
 'JAIME MARTINS',
 'JAIR BOLSONARO',
 'JAIRO ATAÍDE',
 'JANDIRA FEGHALI',
 'JANETE CAPIBERIBE',
 'JANETE ROCHA PIETÁ',
 'JAQUELINE RORIZ',
 'JARBAS VASCONCELOS',
 'JEAN WYLLYS',
 'JEFFERSON CAMPOS',
 'JERÔNIMO GOERGEN',
 'JESUS RODRIGUES',
 'JHC',
 'JHONATAN DE JESUS',
 'JOAQUIM PASSARINHO',
 'JONES MARTINS',
 'JONY MARCOS',
 'JORGE BITTAR',
 'JORGE BOEIRA',
 'JORGE CÔRTE REAL',
 'JORGE SOLLA',
 'JORGE TADEU MUDALEN',
 'JORGINHO MELLO',
 'JOSE STÉDILE',
 'JOSEPH BANDEIRA',
 'JOSI NUNES',
 'JOSUÉ BENGTSON',
 'JOSÉ AIRTON CIRILO',
 'JOSÉ ANÍBAL',
 'JOSÉ AUGUSTO MAIA',
 'JOSÉ CARLOS ALELUIA',
 'JOSÉ CARLOS ARAÚJO',
 'JOSÉ CHAVES',
 'JOSÉ FOGAÇA',
 'JOSÉ GUIMARÃES',
 'JOSÉ HUMBERTO',
 'JOSÉ LINHARES',
 'JOSÉ MENTOR',
 'JOSÉ NUNES',
 'JOSÉ OTÁVIO GERMANO',
 'JOSÉ PRIANTE',
 'JOSÉ REINALDO',
 'JOSÉ ROCHA',
 'JOVAIR ARANTES',
 'JOZI ARAÚJO',
 'JOÃO ANANIAS',
 'JOÃO ARRUDA',
 'JOÃO BITTAR',
 'JOÃO CAMPOS',
 'JOÃO CARLOS BACELAR',
 'JOÃO CASTELO',
 'JOÃO DANIEL',
 'JOÃO DERLY',
 'JOÃO FERNANDO COUTINHO',
 'JOÃO GUALBERTO',
 'JOÃO MAGALHÃES',
 'JOÃO MAIA',
 'JOÃO MARCELO SOUZA',
 'JOÃO PAULO KLEINÜBING',
 'JOÃO PAULO LIMA',
 'JOÃO PAULO PAPA',
 'JOÃO RODRIGUES',
 'JULIO LOPES',
 'JULIÃO AMIN',
 'JUNIOR MARRECA',
 'JUNJI ABE',
 'JUSCELINO FILHO',
 'JUTAHY JUNIOR',
 'JÂNIO NATAL',
 'JÉSSICA SALES',
 'JÔ MORAES',
 'JÚLIA MARINHO',
 'JÚLIO CAMPOS',
 'JÚLIO CESAR',
 'JÚLIO DELGADO',
 'JÚNIOR COIMBRA',
 'KAIO MANIÇOBA',
 'KEIKO OTA',
 'LAEL VARELLA',
 'LAERCIO OLIVEIRA',
 'LAERTE BESSA',
 'LAUDIVIO CARVALHO',
 'LAURA CARNEIRO',
 'LAURIETE',
 'LEANDRE',
 'LEANDRO VILELA',
 'LELO COIMBRA',
 'LEO DE BRITO',
 'LEONARDO MONTEIRO',
 'LEONARDO PICCIANI',
 'LEONARDO QUINTÃO',
 'LEOPOLDO MEYER',
 'LEÔNIDAS CRISTINO',
 'LID.GOV-CD',
 'LIDERANÇA DO PSDB',
 'LIDERANÇA DO PT',
 'LILIAM SÁ',
 'LINCOLN PORTELA',
 'LINDOMAR GARÇON',
 'LIRA MAIA',
 'LOBBE NETO',
 'LOURIVAL GOMES',
 'LOURIVAL MENDES',
 'LUANA COSTA',
 'LUCAS VERGILIO',
 'LUCI CHOINACKI',
 'LUCIANA SANTOS',
 'LUCIANO CASTRO',
 'LUCIANO DUCCI',
 'LUCIANO PIZZATTO',
 'LUCIO MOSQUINI',
 'LUCIO VIEIRA LIMA',
 'LUIS CARLOS HEINZE',
 'LUIS TIBÉ',
 'LUIZ ALBERTO',
 'LUIZ ARGÔLO',
 'LUIZ CARLOS',
 'LUIZ CARLOS BUSATO',
 'LUIZ CARLOS HAULY',
 'LUIZ CARLOS RAMOS',
 'LUIZ CLÁUDIO',
 'LUIZ COUTO',
 'LUIZ DE DEUS',
 'LUIZ FERNANDO FARIA',
 'LUIZ FERNANDO MACHADO',
 'LUIZ LAURO FILHO',
 'LUIZ NISHIMORI',
 'LUIZ OTAVIO',
 'LUIZ PITIMAN',
 'LUIZ SÉRGIO',
 'LUIZA ERUNDINA',
 'LUIZIANNE LINS',
 'LÁZARO BOTELHO',
 'LÉO OLIVEIRA',
 'LÚCIO VALE',
 'MACEDO',
 'MAGDA MOFATTO',
 'MAGELA',
 'MAIA FILHO',
 'MAJOR FÁBIO',
 'MAJOR OLIMPIO',
 'MANDETTA',
 'MANOEL ANTUNES',
 'MANOEL JUNIOR',
 'MANOEL SALVIANO',
 'MANUEL ROSA NECA',
 "MANUELA D'ÁVILA",
 'MARA GABRILLI',
 'MARCELINHO CARIOCA',
 'MARCELO AGUIAR',
 'MARCELO ARO',
 'MARCELO BELINATI',
 'MARCELO CASTRO',
 'MARCELO DELAROLI',
 'MARCELO MATOS',
 'MARCELO SQUASSONI',
 'MARCELO ÁLVARO ANTÔNIO',
 'MARCIO ALVINO',
 'MARCIO BITTAR',
 'MARCIO JUNQUEIRA',
 'MARCO ANTÔNIO CABRAL',
 'MARCO MAIA',
 'MARCO TEBALDI',
 'MARCON',
 'MARCONDES GADELHA',
 'MARCOS ABRÃO',
 'MARCOS LIMA',
 'MARCOS MEDRADO',
 'MARCOS MONTES',
 'MARCOS REATEGUI',
 'MARCOS ROGÉRIO',
 'MARCOS ROTTA',
 'MARCOS SOARES',
 'MARCUS PESTANA',
 'MARCUS VICENTE',
 'MARGARIDA SALOMÃO',
 'MARIA DO ROSÁRIO',
 'MARIA HELENA',
 'MARIA LUCIA PRANDI',
 'MARIANA CARVALHO',
 'MARINALDO ROSENDO',
 'MARINHA RAUPP',
 'MARLLOS SAMPAIO',
 'MARQUINHO MENDES',
 'MARX BELTRÃO',
 'MARÇAL FILHO',
 'MASSAMI MIKI',
 'MAURO BENEVIDES',
 'MAURO LOPES',
 'MAURO MARIANI',
 'MAURO PEREIRA',
 'MAURÍCIO ALMEIDA',
 'MAURÍCIO QUINTELLA LESSA',
 'MAURÍCIO TRINDADE',
 'MAX FILHO',
 'MENDONÇA FILHO',
 'MENDONÇA PRADO',
 'MERLONG SOLANO',
 'MIGUEL HADDAD',
 'MIGUEL LOMBARDI',
 'MILTON MONTI',
 'MIRIQUINHO BATISTA',
 'MISAEL VARELLA',
 'MISSIONÁRIO JOSÉ OLIMPIO',
 'MOEMA GRAMACHO',
 'MOISÉS DINIZ',
 'MOREIRA MENDES',
 'MORONI TORGAN',
 'MOSES RODRIGUES',
 'MÁRCIO BIOLCHI',
 'MÁRCIO MACÊDO',
 'MÁRCIO MARINHO',
 'MÁRIO FEITOZA',
 'MÁRIO HERINGER',
 'MÁRIO NEGROMONTE JR.',
 'NARCIO RODRIGUES',
 'NELSON MARCHEZAN JUNIOR',
 'NELSON MARQUEZELLI',
 'NELSON MEURER',
 'NELSON NAHIM',
 'NELSON PADOVANI',
 'NELSON PELLEGRINO',
 'NEWTON CARDOSO',
 'NEWTON CARDOSO JR',
 'NEWTON LIMA',
 'NILDA GONDIM',
 'NILMÁRIO MIRANDA',
 'NILSON LEITÃO',
 'NILSON PINTO',
 'NILTO TATTO',
 'NILTON CAPIXABA',
 'NIVALDO ALBUQUERQUE',
 'NORMA AYUB',
 'ODELMO LEÃO',
 'ODORICO MONTEIRO',
 'ODÍLIO BALBINOTTI',
 'OLIVEIRA FILHO',
 'ONOFRE SANTO AGOSTINI',
 'ONYX LORENZONI',
 'ORLANDO SILVA',
 'OSMAR BERTOLDI',
 'OSMAR JÚNIOR',
 'OSMAR SERRAGLIO',
 'OSMAR TERRA',
 'OSVALDO COELHO',
 'OSVALDO REIS',
 'OTAVIO LEITE',
 'OTONIEL LIMA',
 'OZIEL OLIVEIRA',
 'PADRE JOÃO',
 'PADRE TON',
 'PAES LANDIM',
 'PASTOR EURICO',
 'PASTOR LUCIANO BRAGA',
 'PATRUS ANANIAS',
 'PAUDERNEY AVELINO',
 'PAULO ABI-ACKEL',
 'PAULO AZI',
 'PAULO BORNHAUSEN',
 'PAULO FEIJÓ',
 'PAULO FOLETTO',
 'PAULO FREIRE',
 'PAULO HENRIQUE LUSTOSA',
 'PAULO MAGALHÃES',
 'PAULO MALUF',
 'PAULO MARTINS',
 'PAULO PEREIRA DA SILVA',
 'PAULO PIMENTA',
 'PAULO RUBEM SANTIAGO',
 'PAULO TEIXEIRA',
 'PAULÃO',
 'PDT',
 'PEDRO CHAVES',
 'PEDRO CUNHA LIMA',
 'PEDRO EUGÊNIO',
 'PEDRO FERNANDES',
 'PEDRO NOVAIS',
 'PEDRO PAULO',
 'PEDRO UCZAI',
 'PEDRO VILELA',
 'PENNA',
 'PEPE VARGAS',
 'PERPÉTUA ALMEIDA',
 'PHS',
 'PINTO DE LUNA',
 'PINTO ITAMARATY',
 'POLICARPO',
 'POLLYANA GAMA',
 'POMPEO DE MATTOS',
 'PR. MARCO FELICIANO',
 'PROFESSOR SETIMO',
 'PROFESSOR SÉRGIO DE OLIVEIRA',
 'PROFESSOR VICTÓRIO GALLI',
 'PROFESSORA DORINHA SEABRA REZENDE',
 'PROFESSORA MARCIVANIA',
 'PROS',
 'PSOL',
 'PTN',
 'RAFAEL MOTTA',
 'RAIMUNDO GOMES DE MATOS',
 'RAQUEL MUNIZ',
 'RAUL JUNGMANN',
 'RAUL LIMA',
 'REBECCA GARCIA',
 'REGINALDO LOPES',
 'REINHOLD STEPHANES',
 'REJANE DIAS',
 'REMÍDIO MONAI',
 'RENATA ABREU',
 'RENATO ANDRADE',
 'RENATO MOLLING',
 'RENATO SIMÕES',
 'RENZO BRAZ',
 'RICARDO BARROS',
 'RICARDO BENTINHO',
 'RICARDO IZAR',
 'RICARDO TEOBALDO',
 'RICARDO TRIPOLI',
 'ROBERTO ALVES',
 'ROBERTO BALESTRA',
 'ROBERTO BRITTO',
 'ROBERTO DE LUCENA',
 'ROBERTO DORNER',
 'ROBERTO FREIRE',
 'ROBERTO GÓES',
 'ROBERTO SALES',
 'ROBERTO SANTIAGO',
 'ROBERTO TEIXEIRA',
 'ROBINSON ALMEIDA',
 'ROCHA',
 'ROCHA LOURES',
 'RODRIGO BETHLEM',
 'RODRIGO DE CASTRO',
 'RODRIGO GARCIA',
 'RODRIGO MAIA',
 'RODRIGO MARTINS',
 'RODRIGO PACHECO',
 'ROGÉRIO CARVALHO',
 'ROGÉRIO MARINHO',
 'ROGÉRIO PENINHA MENDONÇA',
 'ROGÉRIO ROSSO',
 'ROMÁRIO',
 'RONALDO BENEDET',
 'RONALDO CAIADO',
 'RONALDO CARLETTO',
 'RONALDO FONSECA',
 'RONALDO LESSA',
 'RONALDO MARTINS',
 'RONALDO NOGUEIRA',
 'RONALDO ZULKE',
 'ROSANE FERREIRA',
 'ROSANGELA GOMES',
 'ROSE DE FREITAS',
 'ROSINHA DA ADEFAL',
 'ROSSONI',
 'ROSY DE SOUSA',
 'ROSÂNGELA CURADO',
 'RUBENS BUENO',
 'RUBENS OTONI',
 'RUBENS PEREIRA JÚNIOR',
 'RUY CARNEIRO',
 'RÔMULO GOUVEIA',
 'RÔNEY NEMER',
 'SABINO CASTELO BRANCO',
 'SALVADOR ZIMBALDI',
 'SAMUEL MOREIRA',
 'SANDES JÚNIOR',
 'SANDRA ROSADO',
 'SANDRO ALEX',
 'SANDRO MABEL',
 'SARAIVA FELIPE',
 'SARNEY FILHO',
 'SDD',
 'SEBASTIÃO BALA ROCHA',
 'SERGIO SOUZA',
 'SERGIO VIDIGAL',
 'SERGIO ZVEITER',
 'SEVERINO NINHO',
 'SHÉRIDAN',
 'SIBÁ MACHADO',
 'SILAS BRASILEIRO',
 'SILAS CÂMARA',
 'SILAS FREIRE',
 'SILVIO COSTA',
 'SILVIO TORRES',
 'SIMONE MORGADO',
 'SIMÃO SESSIM',
 'SORAYA SANTOS',
 'STEFANO AGUIAR',
 'STEPAN NERCESSIAN',
 'SUBTENENTE GONZAGA',
 'SÁGUAS MORAES',
 'SÉRGIO BARRADAS CARNEIRO',
 'SÉRGIO BRITO',
 'SÉRGIO MORAES',
 'SÉRGIO REIS',
 'SÓSTENES CAVALCANTE',
 'TADEU ALENCAR',
 'TAKAYAMA',
 'TAMPINHA',
 'TAUMATURGO LIMA',
 'TELMA PINHEIRO',
 'TENENTE LÚCIO',
 'TEREZA CRISTINA',
 'THIAGO PEIXOTO',
 'TIA ERON',
 'TIRIRICA',
 'TONINHO PINHEIRO',
 'TONINHO WANDSCHEER',
 'ULDURICO JUNIOR',
 'URZENI ROCHA',
 'VAIDON OLIVEIRA',
 'VAL AMÉLIO',
 'VALADARES FILHO',
 'VALDIR COLATTO',
 'VALMIR ASSUNÇÃO',
 'VALMIR PRASCIDELLI',
 'VALTENIR PEREIRA',
 'VANDER LOUBET',
 'VANDERLEI MACRIS',
 'VANDERLEI SIRAQUE',
 'VAZ DE LIMA',
 'VENEZIANO VITAL DO RÊGO',
 'VICENTE ARRUDA',
 'VICENTE CANDIDO',
 'VICENTINHO',
 'VICENTINHO JÚNIOR',
 'VICTOR MENDES',
 'VILALBA',
 'VILMAR ROCHA',
 'VILSON COVATTI',
 'VINICIUS CARVALHO',
 'VINICIUS GURGEL',
 'VITOR LIPPI',
 'VITOR PAULO',
 'VITOR PENIDO',
 'VITOR VALIM',
 'WADIH DAMOUS',
 'WADSON RIBEIRO',
 'WALDENOR PEREIRA',
 'WALDIR MARANHÃO',
 'WALNEY ROCHA',
 'WALTER ALVES',
 'WALTER IHOSHI',
 'WALTER TOSTA',
 'WANDENKOLK GONÇALVES',
 'WASHINGTON REIS',
 'WELITON PRADO',
 'WELLINGTON FAGUNDES',
 'WELLINGTON ROBERTO',
 'WELLINGTON SALGADO',
 'WEVERTON ROCHA',
 'WILLIAM DIB',
 'WILLIAM WOO',
 'WILSON BESERRA',
 'WILSON FILHO',
 'WLADIMIR COSTA',
 'WOLNEY QUEIROZ',
 'YEDA CRUSIUS',
 'ZE CARLOS DA PESCA',
 'ZECA CAVALCANTI',
 'ZECA DIRCEU',
 'ZECA DO PT',
 'ZENAIDE MAIA',
 'ZOINHO',
 'ZÉ AUGUSTO NALIN',
 'ZÉ CARLOS',
 'ZÉ GERALDO',
 'ZÉ SILVA',
 'ZÉ VIEIRA',
 'ÁTILA A. NUNES',
 'ÁTILA LINS',
 'ÁTILA LIRA',
 'ÂNGELO AGNOLIN',
 'ÍRIS DE ARAÚJO']

Those people elected for this term may have been elected before. I want to take into account exepenses that were made in previous mandates.

In [10]:
reimbursements.shape

(1619213, 31)

In [11]:
filtered_reimbursements = reimbursements[reimbursements['congressperson_name'].isin(current_term_congresspeople)]

In [12]:
filtered_reimbursements.shape

(1375556, 31)

In [61]:
keys = ['congressperson_name', 'congressperson_id', 'applicant_id']
grouped_by_representative = filtered_reimbursements.groupby(keys)['total_net_value'].agg([np.sum,len]) \
                                    .reset_index() \
                                    .rename(columns={'total_net_value': 'sum', 
                                                     'len': 'expenses'})

In [62]:
grouped_by_representative_top_5 = grouped_by_representative.sort_values('sum', ascending=False).head().reset_index(drop=True)
grouped_by_representative_top_5

,congressperson_name,congressperson_id,applicant_id,sum,expenses
0,WELLINGTON ROBERTO,74043,1703,3106049.82,883.0
1,CLEBER VERDE,141408,1804,2975434.05,978.0
2,RAIMUNDO GOMES DE MATOS,74216,1244,2860739.64,3785.0
3,RENATO MOLLING,141527,1922,2809970.46,5966.0
4,EFRAIM FILHO,141422,1823,2774536.47,1784.0

Each tof the top 3 conressperson chamber of deputies page:

In [39]:
pd.set_option('display.max_colwidth', -1) # setting pandas so it won't truncate the html

congressperson_url = '<a href="http://www.camara.leg.br/internet/deputado/dep_Detalhe.asp?id={0}">link</a>'
grouped_by_representative_top_5['url'] = grouped_by_representative_top_5\
                                    .apply(lambda row: congressperson_url.format(row['congressperson_id']), axis=1)
grouped_by_representative_top_5

,congressperson_name,congressperson_id,applicant_id,sum,url
0,WELLINGTON ROBERTO,74043,1703,3106049.82,"<a href=""http://www.camara.leg.br/internet/deputado/dep_Detalhe.asp?id=74043"">link</a>"
1,CLEBER VERDE,141408,1804,2975434.05,"<a href=""http://www.camara.leg.br/internet/deputado/dep_Detalhe.asp?id=141408"">link</a>"
2,RAIMUNDO GOMES DE MATOS,74216,1244,2860739.64,"<a href=""http://www.camara.leg.br/internet/deputado/dep_Detalhe.asp?id=74216"">link</a>"
3,RENATO MOLLING,141527,1922,2809970.46,"<a href=""http://www.camara.leg.br/internet/deputado/dep_Detalhe.asp?id=141527"">link</a>"
4,EFRAIM FILHO,141422,1823,2774536.47,"<a href=""http://www.camara.leg.br/internet/deputado/dep_Detalhe.asp?id=141422"">link</a>"

In [40]:
from IPython.display import HTML
HTML(grouped_by_representative_top_5.to_html(escape=False))

Interesting enough none of the top 5 is Bonifacio Andrada our lower house representative with the highest number of suspicions. So let's load the suspicions file and investigate a little further.

In [19]:
suspicions = pd.read_csv('../data/2017-07-04-suspicions.xz')
suspicions.head()

,applicant_id,year,document_id,meal_price_outlier,over_monthly_subquota_limit,suspicious_traveled_speed_day,invalid_cnpj_cpf,election_expenses,irregular_companies_classifier
0,1001,2009,1564212,False,False,False,False,False,False
1,1001,2009,1564223,False,False,False,False,False,False
2,1001,2009,1568039,False,False,False,False,False,False
3,1001,2009,1568056,False,False,False,False,False,False
4,1001,2009,1568098,False,False,False,False,False,False

In [20]:
suspicions.shape

(1619213, 9)

Now let's filter suspicions from the role suspicions dataset that correspond to our current term.

In [21]:
current_term_aplicant_ids = list(set(current_term_reimbursements['applicant_id']))
suspicions_current_term = suspicions[suspicions['applicant_id'].isin(current_term_aplicant_ids)]
suspicions_current_term.shape

(1375556, 9)

In [22]:
# this takes a lot of time! grab a cup of coffee
def is_suspect(row):
    return row.any()

suspicions_current_term['suspicious'] = suspicions_current_term.apply(lambda row: is_suspect(row[3:]), axis=1)

/home/cabral/anaconda3/envs/serenata_de_amor/lib/python3.5/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [23]:
only_suspicions_current_term = suspicions_current_term[suspicions_current_term['suspicious']]

In [24]:
suspicions_current_term.shape

(1375556, 10)

In [25]:
only_suspicions_current_term.shape

(7125, 10)

In [ ]:
# companies = pd.read_csv('../data/2017-05-21-companies-no-geolocation.xz', low_memory=False)

In [29]:
current_term_applicant_ids = list(set(only_suspicions_current_term['applicant_id']))

In [31]:
len(current_term_aplicant_ids)

808

In [32]:
keys = ['applicant_id']
grouped_by_applicant = only_suspicions_current_term.groupby(keys)['suspicious'].agg(len) \
                                    .reset_index()

In [55]:
grouped_by_applicant = grouped_by_applicant.sort_values('suspicious', ascending=False).head().reset_index(drop=True)
grouped_by_applicant

   applicant_id  suspicious
0  1689          346
1  191           132
2  1010          112
3  2439          103
4  1953          103

In [66]:
top_5 = list(grouped_by_applicant.head()['applicant_id']) 
top_5 = list(map(str,top_5))
top_5

['1689', '191', '1010', '2439', '1953']

In [77]:
top_5_with_suspicions = grouped_by_representative[grouped_by_representative['applicant_id'].isin(top_5)].head(10)
top_5_with_suspicions

      congressperson_name congressperson_id applicant_id         sum  expenses
103  BONIFÁCIO DE ANDRADA  74650             191          1135253.08  1958.0
211  EDUARDO BARBOSA       74655             1010         2308970.72  7829.0
692  SANDRA ROSADO         74039             1689         1552162.38  5463.0
759  VITOR PENIDO          141557            1953         1641426.97  1632.0

In [73]:
reimbursements[reimbursements['applicant_id']=='2439'].head(1)

,year,applicant_id,document_id,reimbursement_value_total,total_net_value,reimbursement_numbers,congressperson_name,congressperson_id,congressperson_document,term,...,issue_date,document_value,remark_value,net_values,month,installment,passenger,leg_of_the_trip,batch_number,reimbursement_values
571822,2011,2439,2176355,0.0,138.0,3753,LIDERANÇA DO PT,NaN,NaN,0.0,...,2011-10-03 00:00:00,138.0,0.0,138.0,10,0,NaN,NaN,569094,0.0

On TOP_5 doesn't show 'LIDERANÇA DO PT' because we'd filtered by congressperson_id. Make sense now since the leadership have special powers with the reimbursments. We MUST save this informations for future analysis like phantom enterprises and other analysis.